server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://ISW-220521-608\\SQLEXPRESS;integratedSecurity=true;encrypt=false;databaseName=Hospital
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate.ddl-auto: validate
  application:
    name: hospital-service
  config:
    import: "optional:configserver:http://localhost:8088"

